# Generated by Django 5.0.2 on 2024-02-23 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_chatmessage_options_remove_chatmessage_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(blank=True, default='default_user.png', null=True, upload_to=''),
        ),
    ]
